{
  sops = {
    defaultSopsFile = ../../sercets/secrets.yaml;
    defaultSopsFormat = "yaml";
    age.sshKeyPaths = [
      "etc/ssh/ssh_host_ed25519_key"
    ];
    age.keyFile = "~/.config/sops/age/keys.txt"
    # I need to finish this later...
    # secrets.
  };


}
